# Generated by Django 2.2.2 on 2019-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='m_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
