# Generated by Django 2.2.2 on 2019-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20190701_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date_of_creation',
            field=models.DateField(),
        ),
    ]
